### ISSUE TITLE
OpenPool is not working on my mac book pro

### ISSUE THREAD

**Issue by giwa** [openpool/openpool-core#24]
My environment is as follows;
- OS X 10.8.4
- Java
  java version "1.7.0_17"
  Java(TM) SE Runtime Environment (build 1.7.0_17-b02)
  Java HotSpot(TM) 64-Bit Server VM (build 23.7-b01, mixed mode)

I tried to run OpenPoolExampleImageOnBall and OpenPoolExample. However they were not running.
- OpenPoolExampleImageOnBall, 
  Error:

multiple Class-Path headers in manifest of jar file: /Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp.jar
multiple Class-Path headers in manifest of jar file: /Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv.jar
multiple Class-Path headers in manifest of jar file: /Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp.jar
multiple Class-Path headers in manifest of jar file: /Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv.jar
java.lang.NumberFormatException: For input string: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Integer.parseInt(Integer.java:449)
    at java.lang.Integer.parseInt(Integer.java:499)
    at processing.app.UpdateCheck.readInt(UpdateCheck.java:134)
    at processing.app.UpdateCheck.updateCheck(UpdateCheck.java:93)
    at processing.app.UpdateCheck$1.run(UpdateCheck.java:63)
    at java.lang.Thread.run(Thread.java:680)
- OpenPoolExample
  Error:
  [0] "Error: This Java instance does not support a 32-bit JVM."
  [1] "Please install the desired version."
  Using startup command:
  {command=command=java -d32 -Xrunjdwp:transport=dt_socket,address=127.0.0.1:8296,suspend=y -Xdock:name=OpenPoolExample -Djava.library.path=:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library:/Users/giwa/Documents/Processing/libraries/SimpleOpenNI/library:/Applications/Processing.app/Contents/Resources/Java:/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Resources:.:/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java -cp /var/folders/cl/d1zr8g750r57lgbnn6g9bzxm0000gn/T/OpenPoolExample7812624295283461873temp:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp-0.3-java-src.zip:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-0.3-java-src.zip:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-android-arm.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-linux-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-linux-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-macosx-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-macosx-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-windows-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-windows-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/OpenPoolCore.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp-0.3-java-src.zip:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacpp.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-0.3-java-src.zip:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-android-arm.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-linux-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-linux-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-macosx-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-macosx-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-windows-x86.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv-windows-x86_64.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/javacv.jar:/Users/giwa/Documents/Processing/libraries/OpenPoolCore/library/OpenPoolCore.jar:/Users/giwa/Documents/Processing/libraries/SimpleOpenNI/library/SimpleOpenNI.jar:/Users/giwa/Documents/Processing/libraries/SimpleOpenNI/library/SimpleOpenNI.jar:/Applications/Processing.app/Contents/Resources/Java/pde.jar:/Applications/Processing.app/Contents/Resources/Java/core.jar:/Applications/Processing.app/Contents/Resources/Java/ant.jar:/Applications/Processing.app/Contents/Resources/Java/ant-launcher.jar:/Applications/Processing.app/Contents/Resources/Java/antlr.jar:/Applications/Processing.app/Contents/Resources/Java/ecj.jar:/Applications/Processing.app/Contents/Resources/Java/jna.jar:/Applications/Processing.app/Contents/Resources/Java/quaqua.jar -ea processing.core.PApplet "--editor-location=260,72" --external --display=0 --sketch-path=/Users/giwa/Documents/Processing/libraries/OpenPoolCore/examples/OpenPoolExample OpenPoolExample , quote=quote=", address=address=127.0.0.1:8296}
- My opinion
  I guess that I have a problem that I installed Java 1.6 in order to use Hadoop on my mac.
  I followed this article (http://lizan.asia/blog/2012/11/13/mountain-lion-setup-hadoop/)

**Comment by giwa** [comment]
Here is the update.
I downloaded Processing 2.0.

I tried to run both of examples. However they are not running on my mac.
- OpenPoolExample
  Error:

2013-06-30 14:33:21.224 java[62839:262f] Can't open input server /Library/InputManagers/MultiClutchInputManager.bundle
The class openpool.DummyPool is incompatible with Processing 2.0.
A library (or other code) is using registerMouseEvent() which is no longer available.
A library (or other code) is using registerKeyEvent() which is no longer available.
SimpleOpenNI Version 0.27
cam1_xoffset:0
cam1_yoffset:0
- OpenPoolExampleOnBall
  Error:

Cannot find anything named "ENABLE_OPENGL_4X_SMOOTH" 

So, I comment out   hint( ENABLE_OPENGL_4X_SMOOTH );

There is Error again
Error
2013-06-30 14:40:23.613 java[62951:281f] Can't open input server /Library/InputManagers/MultiClutchInputManager.bundle
The class openpool.OpenPool is incompatible with Processing 2.0.
A library (or other code) is using registerMouseEvent() which is no longer available.
Stopping the sketch because this code will not work correctly with OpenGL.
java.lang.RuntimeException: java.lang.RuntimeException: This sketch uses a library that needs to be updated for Processing 2.0.
    at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
    at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:100)
    at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:205)
    at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
    at javax.media.opengl.Threading.invoke(Threading.java:191)
    at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:483)
    at processing.opengl.PGL.requestDraw(PGL.java:1155)
    at processing.opengl.PGraphicsOpenGL.requestDraw(PGraphicsOpenGL.java:1602)
    at processing.core.PApplet.run(PApplet.java:2141)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.RuntimeException: This sketch uses a library that needs to be updated for Processing 2.0.
    at processing.core.PApplet.reportDeprecation(PApplet.java:1407)
    at processing.core.PApplet.registerMouseEvent(PApplet.java:1417)
    at openpool.OpenPool.<init>(Unknown Source)
    at openpool.OpenPool.<init>(Unknown Source)
    at OpenPoolExampleImageOnBall.setup(OpenPoolExampleImageOnBall.java:79)
    at processing.core.PApplet.handleDraw(PApplet.java:2245)
    at processing.opengl.PGL$PGLListener.display(PGL.java:2643)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:576)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:561)
    at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:1054)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1024)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:899)
    at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1065)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:708)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:669)
    at java.awt.EventQueue$2.run(EventQueue.java:667)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:678)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
